### PR TITLE
Added Realme C2

### PR DESCRIPTION
**Pull request by siddhrsh**
need some more preference value can you give available lines or guide for that??

### CODE REVIEW

**Comment by phhusson** [comment]
Which preferences do you need?

**Comment by siddhrsh** [comment]
> Which preferences do you need?
from misc force alternative backlight scale
from oppo features DT2W,game mode & otg

**Comment by phhusson** [comment]
Alternative backlight scale is: key_misc_backlight_scale
cf https://github.com/phhusson/treble_app/blob/master/app/src/main/res/xml/pref_misc.xml#L72

Oppo DT2W is key_oppo_double_tap_to_wake
Oppo game mode is key_oppo_ts_game_mode
Oppo OTG is key_oppo_usb_otg

cf https://github.com/phhusson/treble_app/blob/master/app/src/main/res/xml/pref_oppo.xml

**Comment by siddhrsh** [comment]
> Alternative backlight scale is: key_misc_backlight_scale
> cf https://github.com/phhusson/treble_app/blob/master/app/src/main/res/xml/pref_misc.xml#L72
> 
> Oppo DT2W is key_oppo_double_tap_to_wake
> Oppo game mode is key_oppo_ts_game_mode
> Oppo OTG is key_oppo_usb_otg
> 
> cf https://github.com/phhusson/treble_app/blob/master/app/src/main/res/xml/pref_oppo.xml

thank you all lines added you can merge

**Pull request merged**
